# Generated by Django 4.0.1 on 2022-01-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_review_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='article',
            new_name='news',
        ),
    ]
