# Generated by Django 4.0.1 on 2022-01-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_likes_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
