# Generated by Django 4.0.1 on 2022-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_author_article_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
