# Generated by Django 4.0.1 on 2022-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_like_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
