# Generated by Django 4.0.1 on 2022-04-20 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0011_category_news_remove_like_article_remove_like_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.AddField(
            model_name='news',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
